baseurl: ""
url: "https://zhang-yu-wei.github.io"
title: "Yuwei Zhang"
description: "Yuwei Zhang's academic homepage"

markdown: kramdown
plugins:
  - jekyll-email-protect

kramdown:
  input: GFM

timezone: America/Los_Angeles

collections:
  - publications
  - news
  - showcase
  - posts

exclude:
  - _legacy_academic_pages
  - .bundle
  - vendor
  - node_modules
  - Gemfile.lock
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
